

tkrzw:
	git clone https://github.com/estraier/tkrzw-python.git --depth 1
	cd tkrzw-python && make 
	cd tkrzw-python && make install

	wget https://dbmx.net/dict/union-dict-data.tar.gz
	tar -xzf union-dict-data.tar.gz

clean:
	rm -rf tkrzw* union*